# Generated by Django 4.0.3 on 2022-04-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_claimbill_apl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Age1',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='Age2',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='Age3',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='advance',
            field=models.CharField(default='NA', max_length=122),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='AC',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='ACtype',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='IFSC',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='aadhar',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='bankname',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='department',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='designation',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='email',
            field=models.EmailField(default='user@iitk.ac.in', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='mobile',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='rollno',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
