# Generated by Django 4.0.3 on 2022-03-20 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=122)),
                ('project_number', models.IntegerField()),
                ('name', models.CharField(max_length=122)),
                ('roll_number', models.IntegerField()),
                ('designation', models.CharField(max_length=122)),
                ('department', models.CharField(max_length=122)),
                ('pay_band', models.IntegerField()),
                ('purpose', models.TextField()),
                ('travel_cost', models.IntegerField(default=0)),
                ('road_kms', models.IntegerField(default=0)),
                ('hospitality_availed', models.IntegerField(default=0)),
                ('hospitality_not_availed', models.IntegerField(default=0)),
                ('expenses', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('less_advance', models.IntegerField(default=0)),
                ('net', models.IntegerField(default=0)),
                ('name1', models.CharField(default='NA', max_length=122)),
                ('name2', models.CharField(default='NA', max_length=122)),
                ('name3', models.CharField(default='NA', max_length=122)),
                ('name4', models.CharField(default='NA', max_length=122)),
                ('name5', models.CharField(default='NA', max_length=122)),
                ('date1', models.DateField(default=datetime.date(2022, 3, 20))),
                ('date2', models.DateField(default=datetime.date(2022, 3, 20))),
                ('date3', models.DateField(default=datetime.date(2022, 3, 20))),
                ('date4', models.DateField(default=datetime.date(2022, 3, 20))),
                ('date5', models.DateField(default=datetime.date(2022, 3, 20))),
                ('age1', models.IntegerField(default=0)),
                ('age2', models.IntegerField(default=0)),
                ('age3', models.IntegerField(default=0)),
                ('age4', models.IntegerField(default=0)),
                ('age5', models.IntegerField(default=0)),
                ('rel1', models.CharField(default='NA', max_length=122)),
                ('rel2', models.CharField(default='NA', max_length=122)),
                ('rel3', models.CharField(default='NA', max_length=122)),
                ('rel4', models.CharField(default='NA', max_length=122)),
                ('rel5', models.CharField(default='NA', max_length=122)),
                ('part1', models.CharField(default='NA', max_length=122)),
                ('part2', models.CharField(default='NA', max_length=122)),
                ('part3', models.CharField(default='NA', max_length=122)),
                ('part4', models.CharField(default='NA', max_length=122)),
                ('part5', models.CharField(default='NA', max_length=122)),
                ('amt1', models.IntegerField(default=0)),
                ('amt2', models.IntegerField(default=0)),
                ('amt3', models.IntegerField(default=0)),
                ('amt4', models.IntegerField(default=0)),
                ('amt5', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('rollno', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('bankname', models.CharField(max_length=30)),
                ('ACtype', models.CharField(max_length=10)),
                ('AC', models.CharField(max_length=20)),
                ('IFSC', models.CharField(max_length=20)),
                ('aadhar', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
