# Generated by Django 4.0.3 on 2022-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Age1',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='Age2',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='Age3',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='advance',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='basic_pay',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='block_yr',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='departure',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='duration',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='application',
            name='joining',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='age1',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='age2',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='age3',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='age4',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='age5',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='amt1',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='amt2',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='amt3',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='amt4',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='amt5',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='date1',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='date2',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='date3',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='date4',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='date5',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='form',
            name='expenses',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='hospitality_availed',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='hospitality_not_availed',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='less_advance',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='net',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='pay_band',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='project_number',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='road_kms',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='roll_number',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='total',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='form',
            name='travel_cost',
            field=models.CharField(default='', max_length=122),
        ),
    ]
