# Generated by Django 4.0.3 on 2022-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_application_age1_alter_application_age2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='user@iitk.ac.in', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='user@iitk.ac.in', max_length=30, unique=True),
        ),
    ]
