# Generated by Django 4.0.3 on 2022-03-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_application_email_form_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='drivelink',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
