# Generated by Django 4.0.3 on 2022-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_form_drivelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
