from django.db import models
from email.policy import default


# Create your models here.

class Form(models.Model):
    institute=models.CharField(max_length=122)
    email=models.EmailField(default='user@iitk.ac.in',max_length=30,unique=True)
    project_number=models.CharField(max_length=122)
    name=models.CharField(max_length=122)
    roll_number=models.CharField(max_length=122)
    designation=models.CharField(max_length=122)
    department=models.CharField(max_length=122)
    pay_band=models.CharField(max_length=122)
    purpose=models.TextField()
    travel_cost=models.CharField( default='', max_length=122)
    road_kms=models.CharField( default='', max_length=122)
    hospitality_availed=models.CharField( default='', max_length=122)
    hospitality_not_availed=models.CharField( default='', max_length=122)
    expenses=models.CharField( default='', max_length=122)
    total=models.CharField( default='', max_length=122)
    less_advance=models.CharField( default='', max_length=122)
    net=models.CharField( default='', max_length=122)
    drivelink=models.CharField(default="NA",max_length=200)
    name1=models.CharField(default='NA', max_length=122)
    name2=models.CharField(default='NA', max_length=122)
    name3=models.CharField(default='NA', max_length=122)
    name4=models.CharField(default='NA', max_length=122)
    name5=models.CharField(default='NA', max_length=122)
    date1=models.CharField(default='NA', max_length=15)
    date2=models.CharField(default='NA', max_length=15)
    date3=models.CharField(default='NA', max_length=15)
    date4=models.CharField(default='NA', max_length=15)
    date5=models.CharField(default='NA', max_length=15)
    age1=models.CharField(default='' , max_length=122)
    age2=models.CharField(default='' , max_length=122)
    age3=models.CharField(default='' , max_length=122)
    age4=models.CharField(default='' , max_length=122)
    age5=models.CharField(default='' , max_length=122)
    rel1=models.CharField(default='NA',max_length=122)
    rel2=models.CharField(default='NA',max_length=122)
    rel3=models.CharField(default='NA',max_length=122)
    rel4=models.CharField(default='NA',max_length=122)
    rel5=models.CharField(default='NA',max_length=122)
    part1=models.CharField(default="NA",max_length=122)
    part2=models.CharField(default="NA",max_length=122)
    part3=models.CharField(default="NA",max_length=122)
    part4=models.CharField(default="NA",max_length=122)
    part5=models.CharField(default="NA",max_length=122)
    amt1=models.CharField(default='' , max_length=122)
    amt2=models.CharField(default='' , max_length=122)
    amt3=models.CharField(default='' , max_length=122)
    amt4=models.CharField(default='' , max_length=122)
    amt5=models.CharField(default='' , max_length=122)
    status=models.BooleanField(default=False)
    def __str__(self):
        return self.email

class User_profile(models.Model):
    name = models.CharField(max_length=30)
    email =models.EmailField(max_length=30,unique=True)
    rollno = models.CharField(max_length=10)
    designation = models.CharField(max_length=30)
    department = models.CharField(max_length=30)
    bankname = models.CharField(max_length=30)
    ACtype = models.CharField(max_length=10)
    AC = models.CharField(max_length=20)
    IFSC = models.CharField(max_length=20)
    aadhar = models.CharField(max_length=15)
    mobile = models.CharField(max_length=15)
    def __str__(self):
        return self.email

class Application(models.Model):
    block_yr=models.CharField(default='' , max_length=122)
    email=models.EmailField(default='user@iitk.ac.in',max_length=30,unique=True)
    joining=models.CharField(default='' , max_length=122)
    basic_pay=models.CharField(default='' , max_length=122)
    Name=models.CharField(default='NA',max_length=122)
    Designation=models.CharField(default='NA',max_length=122)
    section=models.CharField(default='NA',max_length=122)
    avail=models.CharField(default='NA',max_length=122)
    duration=models.CharField(default='' , max_length=122)
    departure=models.CharField(default='' , max_length=122)
    nature=models.CharField(default='NA',max_length=122)
    Purpose=models.CharField(default='NA',max_length=122)
    place=models.CharField(default='NA',max_length=122)
    place1=models.CharField(default='NA',max_length=122)
    address=models.CharField(default='NA',max_length=122)
    mode=models.CharField(default='NA',max_length=122)
    Name1=models.CharField(default='NA',max_length=122)
    Age1=models.CharField(default='' , max_length=122)
    Name2=models.CharField(default='NA',max_length=122)
    Age2=models.CharField(default='' , max_length=122)
    Name3=models.CharField(default='NA',max_length=122)
    Age3=models.CharField(default='' , max_length=122)
    advance=models.CharField(default='' , max_length=122)
    status=models.BooleanField(default=False)
    def __str__(self):
        return self.email